In [2]:
import numpy as np
print(np.__version__)

1.21.5


In [3]:
arr = np.array([1, 2, 3, 4, 5]) 
print(arr)

print(type(arr))
print(arr.dtype)     
np.array([[1,2],[3,4]])

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


array([[1, 2],
       [3, 4]])

In [4]:
np.arange(1,5)

array([1, 2, 3, 4])

In [5]:
x=np.arange(0,11,2)  
print(x)

[ 0  2  4  6  8 10]


In [6]:
np.zeros((3,2))

array([[0.],
       [0.],
       [0.]])

In [7]:
np.ones((3,5))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.full((2,3),8)
    

array([[4, 4, 4],
       [4, 4, 4]])

In [9]:
np.random.rand(2,3)

array([[0.97672616, 0.64471945, 0.38506868],
       [0.57354404, 0.14834056, 0.63658139]])

# shaping an array using .shape attribute

In [10]:
vector=np.arange(5)
print("vector shape:", vector.shape, '\t', vector)
print("dimension:",vector.ndim)

matrix= np.ones([3,2])
print("\n matrix shape:", matrix.shape,'\n', matrix)
print("dimension:",matrix.ndim)

tensor = np.zeros([2, 3, 3])
print("\n Tensor shape:", tensor.shape,'\n', tensor)
print("dimension:",tensor.ndim)

tensor1=np.full((4,2),8)
print("\n tensor shape:", tensor1.shape,'\n', tensor1)
print("dimension:",tensor1.ndim)




vector shape: (5,) 	 [0 1 2 3 4]
dimension: 1

 matrix shape: (3, 2) 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
dimension: 2

 Tensor shape: (2, 3, 3) 
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
dimension: 3

 tensor shape: (4, 2) 
 [[8 8]
 [8 8]
 [8 8]
 [8 8]]
dimension: 2


# Reshaping arrays. We can reshape an array into any compatible dimensions using .reshape .

In [11]:
arr = np.arange(1, 10)
print(arr, '\n')
arr = arr.reshape(3, 3)
print(arr, '\n')
print("minimum element is:", arr.min())
print("maximum element is:", arr.max())

# Reshape back to the original size
arr = arr.reshape(9)
print(arr)

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

minimum element is: 1
maximum element is: 9
[1 2 3 4 5 6 7 8 9]


# to Return evenly spaced numbers over a specified interval use linspace

In [12]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# eye: to create an identity matrix

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [15]:
np.eye(3, k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

# loading a csv file using numpy

In [16]:
arr = np.loadtxt("C:\\Users\\athar123\\Desktop\\test_bca.csv", delimiter=",", dtype=str)
display(arr)



display(arr[2])

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i'],
       ['1', '2', '3']], dtype='<U1')

array(['g', 'h', 'i'], dtype='<U1')

# loading a csv file using pandas

In [17]:
import pandas as pd
from pandas import read_csv

df=pd.read_csv('train.csv')
data=df.values
print(data)

[[1 0 3 ... 7.25 nan 'S']
 [2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 nan 'S']
 ...
 [889 0 3 ... 23.45 nan 'S']
 [890 1 1 ... 30.0 'C148' 'C']
 [891 0 3 ... 7.75 nan 'Q']]


In [18]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# loading already existing datasets using sklearn(scikit-learn) library 

In [33]:
import sklearn
from sklearn.datasets import load_iris
iris= load_iris()
x,y= iris.data, iris.target
print(x,y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [30]:
from sklearn.linear_model import LinearRegression
hypothesis = LinearRegression(positive = True)
hypothesis.fit(x,y)

LinearRegression(positive=True)

In [31]:
print(hypothesis.coef_)

[0.         0.         0.17832294 0.63042101]


# to show max value along an axis using numpy

In [38]:
import numpy as np

table = np.array([    [5, 3, 7, 1],    [2, 6, 7 ,9],     [1, 1, 1, 1],     [4, 3, 2, 0], ])

print(table)
table.max()





[[5 3 7 1]
 [2 6 7 9]
 [1 1 1 1]
 [4 3 2 0]]


9

In [36]:
#with an argument of axis=0, .max() selects the maximum value in each of the four vertical sets of values in table and
#returns an array that has been flattened, or aggregated into a one-dimensional array.
table.max(axis=0)

array([5, 6, 7, 9])

In [37]:
table.max(axis=1)

array([7, 9, 1, 4])

# to demonstrate how fast is numpy in comparison to list

In [21]:
arr=np.arange(1000)
pythlist=list(range(arr))  #typecast range to list
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [22]:
#time taken by list
%time for _ in range(10): [item * 3 for item in pythlist]

Wall time: 8.92 ms


In [23]:
#time taken by numpy array(fast speed bcoz max code of numpy is written in c)
%time for _ in range(10): arr=arr*3

Wall time: 0 ns


Python program to change diagonal elements to 1 in identity matrix

In [19]:
MAX = 100
 
# to print the resultant matrix
def print_1(mat, n, m):
     
    for i in range(n):
        for j in range(m):
            print( mat[i][j], end = " ")
 
        print()
 
# function to change the values
# of diagonal elements to 1
def makediagonalzero(mat, n, m):
 
    for i in range(n):
        for j in range(m):
 
            # right and left diagonal condition
            if (i == j or (i + j+1) == n):
                mat[i][j] = 0
 
    # print resultant matrix
    print_1(mat, n, m)
    
# driver code 
print(__name__)
if __name__ == "__main__":
 
    n = 3
    m = 3
    mat = [[ 2, 3, 7 ],
           [ 3, 7, 2 ],
           [ 5, 4, 9 ]]
 
    makediagonalzero(mat, n, m)

__main__
0 3 0 
3 0 2 
0 4 0 
